# Generated by Django 5.1.11 on 2025-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_domain_is_primary_alter_domain_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
