# Generated by Django 5.1.11 on 2025-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_domain_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_drop_schema',
            field=models.BooleanField(default=False),
        ),
    ]
