# Generated by Django 5.2.3 on 2025-06-30 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ФИО контакта', max_length=100)),
                ('email', models.EmailField(help_text='Email контакта (уникальный в пределах схемы)', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Телефон контакта (опционально)', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
